services:
    php:
        build:
            context: ./
            dockerfile: ./docker/php-fpm/Dockerfile
        environment:
            DB_HOST: database
            DB_DATABASE: laravel_ddd
            DB_USERNAME: laravelddd
            DB_PASSWORD: laravelddd

            DB_HOST_TESTING: database
            DB_DATABASE_TESTING: laravel_ddd_testing
            DB_USERNAME_TESTING: laravelddd
            DB_PASSWORD_TESTING: laravelddd
        volumes:
            - .:/var/www/html

    database:
        image: "mysql:8.3"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravelddd
            MYSQL_PASSWORD: laravelddd
        volumes:
            - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql

    composer:
        image: "composer:2.7.2"
        volumes:
            - .:/app
