services:
    php:
        build:
            context: ./
            dockerfile: ./docker/php-fpm/Dockerfile
        environment:
            DB_CONNECTION: testing
            DB_HOST_TESTING: database
            DB_DATABASE_TESTING: laravel_ddd_testing
            DB_USERNAME_TESTING: laravelddd
            DB_PASSWORD_TESTING: laravelddd
        volumes:
            - .:/var/www/html

    database:
        image: "mysql:8.3"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_ddd_testing
            MYSQL_USER: laravelddd
            MYSQL_PASSWORD: laravelddd

    composer:
        image: "composer:2.7.2"
        volumes:
            - .:/app
