#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- php-fpm "$@"
fi

# Clear Artisan cache
/var/www/html/artisan config:cache --no-ansi --no-interaction

exec "$@"
