name: 'PHP Setup'
description: 'Setup everything for PHP'

inputs:
  php-version:
    description: 'PHP Version'
    required: false
    default: '8.3.0'

runs:
  using: "composite"
  steps:
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.lock') }}

    - name: Install PHP
      uses: shivammathur/setup-php@efffd0e4f2504f936fcfe3b69293d31ce0e2fd7a
      with:
        php-version: ${{ inputs.php-version }}

    - name: Install PHP dependencies
      run: composer install --no-interaction --no-progress
      shell: bash
